title: <p align="center"> Daniel Vargas </p>
favicon: /assets/images/foto.jfif
logo: /assets/images/foto.jfif
logo_height: 100px
logo_width: auto

description:
  <p align="center">
  <a href="assets/dv-resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/danvargg/">LinkedIn</a> |
  <a href="https://github.com/danvargg">GitHub</a>
 
  <br>  
  I am a Machine Learning and AI professional with extensive experience in delivering ML / AI solutions. I am proficient 
  in leveraging machine learning, deep learning, and AI technologies to drive innovation in diverse industries. 
  <br>
  </p>

theme: jekyll-theme-minimal