title: <p align="center"> Daniel Vargas </p>
logo: /assets/picture.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sajan-kedia-b06a6821/">LinkedIn</a> |
  <a href="https://github.com/sajankedia">GitHub</a>
 
  <br>  
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with IBM Research at Big Data Analytics team.
  Working in AdTech domain for 3 years.
  ![Python](https://img.shields.io/badge/-Python-000000?style=flat&logo=Python)
  <br>
  </p>

theme: jekyll-theme-minimal