title: <p align="center"> Daniel Vargas </p>
favicon: /assets/images/foto_port.ico
logo: /assets/images/foto_port.jpeg
logo_height: 100px
logo_width: auto

description:
  <p align="center">
  <a href="assets/dv-resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/danvargg/">LinkedIn</a> |
  <a href="https://github.com/danvargg">GitHub</a>
 
  <br>  
  I am a Machine Learning Engineer with almost a decade of experience delivering ML / AI solutions.
  <br>
  </p>

theme: jekyll-theme-minimal